settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: NAS-server
  path: .
  commands:
    install:
      status: true
      method: go build -o ./build/binary
    run:
      status: true
      method: ./build/binary
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
