app:
  page_size: 10
  jwt_secret: PB!xzaA@1e$A

server:
  run_mode: debug
  http_port: :7001
  read_timeout: 60
  write_timeout: 60
  # 每5秒同步一次数据到数据库
  # save_internal: 5

database:
  # type: mongo
  # host: 118.31.64.23:27017
  host: 127.0.0.1:27017
  db: NAS